In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data=pd.read_csv("uber-raw-data-apr14.csv",parse_dates=[0])
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 564516 entries, 0 to 564515
Data columns (total 4 columns):
Date/Time    564516 non-null datetime64[ns]
Lat          564516 non-null float64
Lon          564516 non-null float64
Base         564516 non-null object
dtypes: datetime64[ns](1), float64(2), object(1)
memory usage: 17.2+ MB


In [3]:
data.head()

Date/Time      Lat      Lon    Base
0 2014-04-01 00:11:00  40.7690 -73.9549  B02512
1 2014-04-01 00:17:00  40.7267 -74.0345  B02512
2 2014-04-01 00:21:00  40.7316 -73.9873  B02512
3 2014-04-01 00:28:00  40.7588 -73.9776  B02512
4 2014-04-01 00:33:00  40.7594 -73.9722  B02512

In [4]:
X=data.iloc[:,1:3]
X.head()

Lat      Lon
0  40.7690 -73.9549
1  40.7267 -74.0345
2  40.7316 -73.9873
3  40.7588 -73.9776
4  40.7594 -73.9722

In [5]:
from sklearn.cluster import MiniBatchKMeans

kmeans=MiniBatchKMeans(4)
kmeans.fit(X)

MiniBatchKMeans(batch_size=100, compute_labels=True, init='k-means++',
        init_size=None, max_iter=100, max_no_improvement=10, n_clusters=4,
        n_init=3, random_state=None, reassignment_ratio=0.01, tol=0.0,
        verbose=0)

In [6]:
kmeans.cluster_centers_

array([[ 40.7324334 , -74.0015978 ],
       [ 40.67789398, -73.77556641],
       [ 40.7690837 , -73.96383164],
       [ 40.68828283, -73.96580835]])

In [7]:
X[kmeans.predict(X)==0]

Lat      Lon
1       40.7267 -74.0345
2       40.7316 -73.9873
5       40.7383 -74.0403
6       40.7223 -73.9887
8       40.7524 -73.9960
10      40.7256 -73.9869
12      40.7271 -73.9803
17      40.7238 -73.9821
18      40.7531 -74.0039
19      40.7389 -74.0393
21      40.7530 -74.0042
23      40.7250 -73.9844
24      40.6950 -74.1783
26      40.6879 -74.1814
27      40.6878 -74.1816
28      40.7234 -73.9974
29      40.7336 -73.9900
30      40.7141 -74.0094
34      40.7744 -74.0149
35      40.7393 -73.9974
38      40.6907 -74.1782
39      40.7217 -73.9875
41      40.7437 -73.9985
43      40.7430 -74.0301
44      40.7430 -74.0301
45      40.7423 -74.0371
46      40.7236 -74.0037
52      40.7442 -73.9854
53      40.7166 -74.0144
55      40.7337 -73.9979
...         ...      ...
564460  40.7427 -73.9910
564461  40.7326 -74.0084
564464  40.7223 -73.9841
564465  40.7432 -74.0076
564467  40.7368 -73.9996
564470  40.7330 -73.9981
564473  40.7495 -73.9968
564477  40.7528 -73.9853
564478  40.7251 -74.0024
564479  40.7526 -73.9949
564480  40.7405 -74.0059
564482  40.7361 -73.9851
564483  40.7459 -73.9843
564484  40.7209 -74.0042
564485  40.7583 -73.9901
564486  40.7342 -74.0101
564487  40.7412 -73.9792
564490  40.7210 -73.9850
564491  40.7025 -74.0127
564493  40.7446 -73.9837
564495  40.7213 -73.9948
564497  40.7325 -73.9969
564501  40.7436 -73.9848
564502  40.7313 -73.9940
564505  40.7419 -73.9866
564506  40.7316 -73.9891
564507  40.7267 -73.9937
564509  40.7420 -74.0037
564510  40.7514 -74.0066
564513  40.7443 -73.9889

[274849 rows x 2 columns]

In [8]:
from bokeh.io import output_file, show
from bokeh.models import ColumnDataSource, GMapOptions
from bokeh.plotting import gmap

output_file("gmap1.html")

map_options = GMapOptions(lat=40.730610, lng=-73.935242, map_type="roadmap", zoom=11)

# For GMaps to function, Google requires you obtain and enable an API key:
#
#     https://developers.google.com/maps/documentation/javascript/get-api-key
#
# Replace the value below with your personal API key:
p = gmap("AIzaSyB-E81VWnuGE2A9iXgHHI3lz5ZOvbRIN3A", map_options, title="New York")


X=X.sample(1000)
centroid = ColumnDataSource(
    data=dict(lat=kmeans.cluster_centers_[:,0],
             lng=kmeans.cluster_centers_[:,1])
)

cluster_0=ColumnDataSource(
    data=dict(lat=X[kmeans.predict(X)==0].iloc[:,0],
                   lng=X[kmeans.predict(X)==0].iloc[:,1]))
    
cluster_1=ColumnDataSource(
    data=dict(lat=X[kmeans.predict(X)==1].iloc[:,0],
                   lng=X[kmeans.predict(X)==1].iloc[:,1]))

    
cluster_2=ColumnDataSource(
    data=dict(lat=X[kmeans.predict(X)==2].iloc[:,0],
                   lng=X[kmeans.predict(X)==2].iloc[:,1]))

cluster_3=ColumnDataSource(
    data=dict(lat=X[kmeans.predict(X)==3].iloc[:,0],
                   lng=X[kmeans.predict(X)==3].iloc[:,1]))

p.circle(x="lng", y="lat", size=8, fill_color="red", fill_alpha=0.8, source=cluster_0)
p.circle(x="lng", y="lat", size=8, fill_color="yellow", fill_alpha=0.8, source=cluster_1)
p.circle(x="lng", y="lat", size=8, fill_color="purple", fill_alpha=0.8, source=cluster_2)
p.circle(x="lng", y="lat", size=8, fill_color="white", fill_alpha=0.8, source=cluster_3)

p.circle(x="lng", y="lat", size=15, fill_color="blue", fill_alpha=0.8, source=centroid)

show(p)

In [9]:
from sklearn.cluster import DBSCAN
dbscan=DBSCAN(eps=0.01,min_samples=10,metric="manhattan")
dbscan.fit(X)

DBSCAN(algorithm='auto', eps=0.01, leaf_size=30, metric='manhattan',
    metric_params=None, min_samples=10, n_jobs=None, p=None)

In [10]:
np.unique(dbscan.labels_,return_counts=True)

(array([-1,  0,  1,  2,  3,  4], dtype=int64),
 array([136, 799,  15,  18,  16,  16], dtype=int64))

In [11]:
X[dbscan.fit_predict(X)==4]

Lat      Lon
460749  40.7204 -73.9632
184624  40.7211 -73.9556
186258  40.7160 -73.9520
271212  40.7186 -73.9588
307027  40.7156 -73.9556
457484  40.7170 -73.9564
417244  40.7127 -73.9586
179126  40.7183 -73.9599
213483  40.7136 -73.9658
457560  40.7124 -73.9641
80764   40.7176 -73.9634
419445  40.7165 -73.9617
43514   40.7189 -73.9587
265143  40.7128 -73.9523
130694  40.7123 -73.9660
512280  40.7138 -73.9493

In [12]:
from bokeh.io import output_file, show
from bokeh.models import ColumnDataSource, GMapOptions
from bokeh.plotting import gmap

output_file("gmap1.html")

map_options = GMapOptions(lat=40.730610, lng=-73.935242, map_type="roadmap", zoom=11)

# For GMaps to function, Google requires you obtain and enable an API key:
#
#     https://developers.google.com/maps/documentation/javascript/get-api-key
#
# Replace the value below with your personal API key:
p = gmap("AIzaSyB-E81VWnuGE2A9iXgHHI3lz5ZOvbRIN3A", map_options, title="New York")



cluster_m1=ColumnDataSource(
    data=dict(lat=X[dbscan.fit_predict(X)==-1].iloc[:,0],
                   lng=X[dbscan.fit_predict(X)==-1].iloc[:,1]))


cluster_0=ColumnDataSource(
    data=dict(lat=X[dbscan.fit_predict(X)==0].iloc[:,0],
                   lng=X[dbscan.fit_predict(X)==0].iloc[:,1]))


cluster_1=ColumnDataSource(
    data=dict(lat=X[dbscan.fit_predict(X)==1].iloc[:,0],
                   lng=X[dbscan.fit_predict(X)==1].iloc[:,1]))


cluster_2=ColumnDataSource(
    data=dict(lat=X[dbscan.fit_predict(X)==2].iloc[:,0],
                   lng=X[dbscan.fit_predict(X)==2].iloc[:,1]))

cluster_3=ColumnDataSource(
    data=dict(lat=X[dbscan.fit_predict(X)==3].iloc[:,0],
                   lng=X[dbscan.fit_predict(X)==3].iloc[:,1]))

cluster_4=ColumnDataSource(
    data=dict(lat=X[dbscan.fit_predict(X)==4].iloc[:,0],
                   lng=X[dbscan.fit_predict(X)==4].iloc[:,1]))

cluster_5=ColumnDataSource(
    data=dict(lat=X[dbscan.fit_predict(X)==5].iloc[:,0],
                   lng=X[dbscan.fit_predict(X)==5].iloc[:,1]))


p.circle(x="lng", y="lat", size=8, fill_color="black", fill_alpha=0.8, source=cluster_m1)

p.circle(x="lng", y="lat", size=8, fill_color="yellow", fill_alpha=0.8, source=cluster_0)

p.circle(x="lng", y="lat", size=8, fill_color="purple", fill_alpha=0.8, source=cluster_1)

p.circle(x="lng", y="lat", size=8, fill_color="white", fill_alpha=0.8, source=cluster_2)

p.circle(x="lng", y="lat", size=8, fill_color="red", fill_alpha=0.8, source=cluster_3)

p.circle(x="lng", y="lat", size=8, fill_color="orange", fill_alpha=0.8, source=cluster_4)


p.circle(x="lng", y="lat", size=8, fill_color="green", fill_alpha=0.8, source=cluster_5)


show(p)